### ISSUE TITLE
CSV로 데이터 업로드 어떨까요?

### ISSUE THREAD

**Issue by benjioh5** [Resten1497/awesome-beer#1]
CSV 파일이 편집에 용이할 듯 합니다!

이후 배치 스크립트나 쉘 스크립트로 md 파일 랜더링이 낫지 않을까요? + 웹에서 갖다 쓰기 좋지 않을까요

**Comment by resten1497** [comment]
![image](https://user-images.githubusercontent.com/19689492/158066177-2c5bf061-a09c-4325-8752-7dbbc624cd53.png)

현재 데이터를 이렇게 취합하고 관리하고 있습니다. 
취합이 완료되면 CSV로 올리는것도 고려해보겠습니다.

**Comment by resten1497** [comment]
https://github.com/Resten1497/awesome-beer/issues/3#issuecomment-1072471470

동일한 issue로 Close 하겠습니다.
