### ISSUE TITLE
기본 README.md 파일 시도 분리

### ISSUE THREAD

**Issue by resten1497** [Resten1497/awesome-beer#7]
생각보다 데이터가 너무 많아져서 (현재 220개 ) 
한페이지에 너무 많은 데이터들이 보이는 이슈가있습니다.
시도별로 분류를 하는편이 더 가독성이 좋을까요?

**Comment by shlee0114** [comment]
한 곳에 있다는 것에 장점도 있다 생각하지만 한 곳에 있다는 것은 나한테 필요없는 정보도 같이 들어온다는 단점이 있어서
나누는게 더 좋다고 생각합니다 나눠야 찾기도 더 편해요

**Comment by resten1497** [comment]
### 안녕하세요 승현님! 좋은 의견 감사합니다!

의견 주신것처럼 업데이트를 통해서 지역단위로 정보를 분할하였습니다.
 https://github.com/Resten1497/awesome-beer/commit/d60ef17be592776582de6a858a0e6eadbc7308ce 이 커밋을 참조하시면 좋을것같아요!

위 작업을 진행 하면서, 전체 CSV 파일 에서 지역을 분리해주는 코드도 작성하여 추가할 수 있었습니다.
좋은 의견 감사합니다! 
추가적인 의견이 있으시면 참고하도록하겠습니다!
